name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: skjerns/buildozer-action@v3
        with:
          command: buildozer -v android debug
          buildozer_version: master

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
